title: "Marine Biology Research Lab"
description: "Exploring ocean ecosystems, coral reefs, and marine biodiversity."
theme: minima
url: "https://sarahnanco.github.io/" # will auto-fill if using GitHub Pages
baseurl: "/nancollaslab"