title: "Marine Biology Lab"
description: "Exploring ocean ecosystems and biodiversity"
url: "https://sarahnanco.github.io"   # replace USERNAME with your GitHub username
baseurl: "/nancollaslab"   # leave empty if this is username.github.io, otherwise "/repo-name"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-include-cache

# Appearance
minimal_mistakes_skin: "mint"

# Defaults so pages render properly
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
