# Site settings
title: "Nancollas Lab"
description: "Research in coral reef ecology, marine biodiversity, and conservation science."
url: "https://sarahnanco.github.io"   # your GitHub Pages base URL
baseurl: "/nancollaslab"              # repo name since this is NOT username.github.io

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

# Appearance (skins: default, air, contrast, dark, dirt, neon, mint, sunrise)
minimal_mistakes_skin: "sunrise"

# Defaults (apply to all pages)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      css: "/nancollaslab/assets/css/custom.css?v=1"   # custom CSS for all pages

# Navigation menu (top links)
header_pages:
  - about.md
  - research.md
  - publications.md
  - team.md
  - contact.md

# Author info (footer + SEO)
author:
  name   : "Dr. Sarah Nancollas"
  avatar : "/nancollaslab/assets/images/avatar.jpg"   # optional
  bio    : "We study marine ecosystems and biodiversity, from coral reefs to the deep sea."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:labemail@university.edu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sarahnanco"

# Custom includes
include:
  - assets/css/custom.css

# Hook custom CSS into the theme
  head_includes:
  - /nancollaslab/assets/css/custom.css
