title: "Marine Biology Lab"
description: "Exploring ocean ecosystems and biodiversity"
url: "https://sarahnanco.github.io"   # your GitHub Pages base URL
baseurl: "/nancollaslab"              # repo name since this is NOT username.github.io

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Minimal Mistakes requires this plugin for performance caching
plugins:
  - jekyll-include-cache

# Appearance (pick from: default, air, contrast, dark, dirt, neon, mint, sunrise)
minimal_mistakes_skin: "mint"

# Default settings for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Navigation links
header_pages:
  - about.md
  - research.md
  - publications.md
  - team.md
  - contact.md
